SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE: float = 0.8  # seconds
ASTEROID_MAX_RADIUS: float = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS: int = 20
