[project]
name = "asteroids"
version = "0.1.0"
description = "Recreation of the famous Asteroids game in PyGame"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame==2.6.1",
]
